### ISSUE TITLE
控件尺寸与图片不匹配

### ISSUE THREAD

**Issue by scavin** [Nigh/PicQuickCompare#1]
拖了两张照片进去，窗口变的比屏幕还大，但...照片还是剧中显示的很小，窗口无法拖拽调整

**Comment by scavin** [comment]
另外，最好能在标题显示文件名，有些相似的照片不好区分

**Comment by scavin** [comment]
<img width="1456" alt="Appinn-2023-08-28-10 51 21@2x" src="https://github.com/Nigh/PicQuickCompare/assets/716584/86d676f0-4be9-4c1d-a1eb-dc3ff250e96f">

这是一张小图，如果原尺寸较大的话，就撑破屏幕了

**Comment by scavin** [comment]
我发现这个问题了，是高清屏的问题，开启`高DPI缩放替代`解决

**Comment by Nigh** [comment]
@scavin 理论上控件大小应该是适配图片的，但是现在就是比图片大一圈。这个项目是从之前一个项目改的，之前就有这个问题，还一直没去查的。

**Comment by Nigh** [comment]
> 另外，最好能在标题显示文件名，有些相似的照片不好区分

在计划中。
